### ISSUE TITLE
UnicodeDecodeError on Python 3 with ASCII locale

### ISSUE THREAD

**Issue by jaraco** [pwdyson/inflect.py#21]
```
vagrant@vagrant-ubuntu-trusty-64:~$ LANG=C python3 -m pip install --user inflect
Downloading/unpacking inflect
  Downloading inflect-0.2.4.tar.gz (91kB): 91kB downloaded
  Running setup.py (path:/tmp/pip_build_vagrant/inflect/setup.py) egg_info for package inflect
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_vagrant/inflect/setup.py", line 9, in <module>
        readme = open(readme_path).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47692: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_vagrant/inflect/setup.py", line 9, in <module>

    readme = open(readme_path).read()

  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 47692: ordinal not in range(128)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_vagrant/inflect
Storing debug log for failure in /home/vagrant/.pip/pip.log
```

**Comment by jaraco** [comment]
This was fixed in the 0.2.5 release. Thanks.
